USA = "United States"
"U.S.A." = "United States"
"United States of America" = "United States"
Massachusettes = "Massachusetts"
"Chicago, Cooks, Illinois" = "Chicago, Cook, Illinois"
"Chicago, Illinois" = "Chicago, Cook, Illinois"
